"""Analyze joined annotations; no human labels are generated by this command."""
import argparse
import json
from pathlib import Path
from cyberredteam.evaluation.scenarios import calibration

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('labels', type=Path)
parser.add_argument('--output', type=Path, required=True)
args = parser.parse_args()
result = calibration(json.loads(args.labels.read_text()))
args.output.parent.mkdir(parents=True, exist_ok=True)
args.output.write_text(json.dumps(result, indent=2))
print(f"Analyzed {result['n']} joined labels; disagreements: {len(result['disagreements'])}")
